### ISSUE TITLE
Unplanned Server Migration 

### ISSUE THREAD

**Issue by Growmore2** [bosagora/agora-chain#41]
if I directly terminate the existing server and create a new server for the node?
erasing the temp wallet of the existing server will cause any problems? or leads to loss of funds?

**Comment by MichaelKim20** [comment]
Is your situation as below?
1. So far, you have imported the validator's key of server A and executed the validator.
2. Currently, you want to run the validator after importing the same validator's key from the B server.

Is this the right situation?
Then I'll give you an answer on this.

You should be careful because running validator's keys on two servers at the same time can cause slashing.
Therefore, you must follow these steps to make changes to the server.

When you attempt to move all validator's keys from server A to server B,
1. Receive both historical data from agora-el and agora-cl and set up the environment so that Server B can run the validator. (See https://github.com/bosagora/agora-chain/blob/mainnet/docs/INSTALL-NODE-UBUNTU-EN.md)
2. You shut down all of server A's agora-el-node, agora-cl-node, and agora-cl-validator.
3. You download the file below from Server A.
    agora-chain-mainnet/root/chain/validator.db
    agora-chain-mainnet/root/wallet/direct/accounts/all-accounts.keystore.json
4. You upload the file to the same place on server B.
5. You wait for about 2 Epoch. (About 12 minutes)
6. You can run the nodes and validator on server B.

If you do not have permission to access the folder, use the command below.
```
sudo chown ubuntu root/chain -R
sudo chown ubuntu root/wallet -R
```

**Comment by MichaelKim20** [comment]
The asset does not exist in the wallet. A wallet is a secret key to access your assets.
Your assets exist in the BOSagora blockchain network. So even if you erase your wallet, your assets don't disappear.

**Comment by Growmore2** [comment]
The validator is running well and was terminated by me mistakenly(without any backup). so if I repeat the same process shown in the video will I be in any problems?

**Comment by MichaelKim20** [comment]
I'll give you some information. See if that's the solution in your case.
And I think it can be resolved faster if you let me know more about your situation in detail.

**1. When you start the nodes and validator client, the command are as follows:**
```
./agora.sh docker-compose up
```

**2. When shutting down nodes and validator  clients, the command are as follows:**
```
./agora.sh docker-compose down
```

**3. How did the validator  client terminate abnormally?**

**4.  If you restart the server**

> If you run as in No.1, the nodes and validator  client will automatically start when the server restarts.** 
> If you restart No.1 at this time, an error will occur.


**5. Use the following command to find out if the program is running or not.**

> To view the execution status of the nodes, check the log using the docker command.
> 
> You can check the log of 'agora-el-node' by executing the command below. Enter ctrl+c to exit.
> ```
> docker logs -f agora-el-node
> ```
> 
> You can check the log of 'agora-cl-node' by executing the command below. Enter ctrl+c to exit.
> ```
> docker logs -f agora-cl-node
> ```
> 
> You can check the log of 'agora-cl-validator' by executing the command below. Enter ctrl+c to exit.
> ```
> docker logs -f agora-cl-validator
> ```

**Comment by Growmore2** [comment]
I'm currently running my node in a low-spec server. so I want to terminate this server and want to shift to after one with the high spec.
so I could like to know the safest and easiest way to transfer all the saved validators to another server I'm running 16 validators in the same node).
(Increasing spec was not the case because i want to change the location of the server too)

**Comment by MichaelKim20** [comment]
When you attempt to move all validator's keys from server A to server B,
1. Receive both historical data from agora-el and agora-cl and set up the environment so that Server B can run the validator. (See https://github.com/bosagora/agora-chain/blob/mainnet/docs/INSTALL-NODE-UBUNTU-EN.md)
2. You shut down all of server A's agora-el-node, agora-cl-node, and agora-cl-validator.
3. You download the file below from Server A.
    ~/agora-chain-mainnet/root/chain/validator.db
    ~/agora-chain-mainnet/root/wallet/direct/accounts/all-accounts.keystore.json
4. You upload the file to the same place on server B.
5. You wait for about 2 Epoch. (About 12 minutes)
6. You can run the nodes and validator on server B.

If you do not have permission to access the folder, use the command below.
```
sudo chown ubuntu root/chain -R
sudo chown ubuntu root/wallet -R
```

**Comment by TrustHenry** [comment]
@Growmore2 Is the issue resolved?

**Comment by Growmore2** [comment]
yes its solved.

i copied all keystones to another server and a new wallet is created.
so while redeeming there wont be issues right ? i can withdraw to new wallet and new wallet to my mainnet wallet right ?
