### ISSUE TITLE
How to Update & Exit?

### ISSUE THREAD

**Issue by bitsandtea** [bosagora/agora-chain#96]
Hello, I followed the instructions [here](https://docs.bosagora.org/en/upgrades/the-withdrawals-upgrade-for-mainnet) 

and I am getting on my execution layer:

`WARN [08-31|09:32:15.180] Served engine_newPayloadV2               reqid=71 duration="96.659µs"  err="Invalid parameters" errdata="{Error:non-nil withdrawals pre-shanghai}"
`

On Validation layer:

`[2023-08-31 09:32:51]  INFO validator: Waiting for beacon node to sync to latest chain head`

and on Consensus layer:

```
[2023-08-31 09:33:38]  WARN initial-sync: Skip processing batched blocks error=beacon node doesn't have a parent in db with root: 0x556705db2ac5c22443317ae9c7abda185611f2a50c21d139ada0a80fc053ab42 (in processBatchedBlocks, slot=1610400)
[2023-08-31 09:33:47]  WARN powchain: Execution client is not syncing

```

I ran the following command on all layers:

`(curl -fsSL https://raw.githubusercontent.com/bosagora/agora-chain/v0.x.x/upgrade.sh)"
`
Start the node.
`./agora.sh start`

this command `./agora.sh start` doesn't work

I managed to generate the bLS keys successfully though and got a partial withdrawal executed. However I am having issues issuing validator exit

**Comment by MichaelKim20** [comment]
Execution layer is not synchronized.
There can be a number of reasons, such as upgrading too late, not running the correct commands, or not completing the upgrade.
Rather than finding the reason, I recommend you start anew.

1. Please upgrade it first
```
./agora.sh upgrade
```
or
```
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/bosagora/agora-chain/v0.x.x/upgrade.sh)"
```

2. Initialize and synchronize the execution layer
```
./agora.sh el-node init
./agora.sh el-node run
```

3. Connect to a different terminal.
And reset and synchronize the consensus layer
```
./agora.sh cl-node clear-db
./agora.sh cl-node run
```

4. Verify that the synchronization of the execution layer and the consensus layer is complete.
Then, after exiting the execution layer and consensus layer, execute the command below.
```
./agora.sh start
```
